name: Node.js Package
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to GitHub Packages
    - uses: actions/setup-node@v2
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'
        # Defaults to the user or organization that owns the workflow file
        scope: '@traveldealz'
    - name: Change name in package.json
      run: sed -i 's/wcd\/goaround\./traveldealz\//g' package.json
    - name: Change version in package.json
      env:
        RELEASE_TAG: ${{ github.event.release.tag_name }}
      run: sed -i 's/"version":"" "1.0.0"/"version":"" "$RELEASE_TAG"/g' package.json
    - name: Publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm publish
